### ISSUE TITLE
Upstream False Flags

### ISSUE THREAD

**Issue by Parsonswy** [peacefulcraft-network/BasicAntiCheat#5]
Upstream repository has several false flag reports that need to be verified and fixed if found to be an issue.

- [ ] Speed check when sprinting over water with depthstrider and dolphins grace. [#6](https://github.com/MC-Jinky/BasicAntiCheat/issues/6)
- [ ] Anticactus when moving back and forth with sneak [#5](https://github.com/MC-Jinky/BasicAntiCheat/issues/5)
- [ ] Anticheat disabler vulnerability [#3](https://github.com/MC-Jinky/BasicAntiCheat/issues/3)
